### ISSUE TITLE
Add time_zone support in MsgPack

### ISSUE THREAD

**Issue by schmidtw** [Comcast/aker#100]
- [ ] Add `time_zone` type string to MsgPack structure
- [ ] Add the code to actually use the new timezone data as described below (for the weekly schedule times only).

Suggested place to start:
```
int main (int argc, char *argv[])
{
   struct tm *mt;
   time_t mtt;
   char ftime[10];

   setenv("TZ", "America/New_York", 1);
   tzset();
   mtt = time(NULL);
   mt = localtime(&mtt);
   strftime(ftime,sizeof(ftime),"%Z %H%M",mt);

   printf("%s\n", ftime);
}
```

**Comment by manderiasian** [comment]
OK this is done. However, I am a little confused. Why do we need the time_zone? The only reason I see is if we need to know DST, and I am not even sure about that.
Since "absolutes" times are given to us in UTC, if we use time() we also get UTC, so the only adjustment is possibly to apply DST ...

**Comment by schmidtw** [comment]
The `time_zone` is there for the weekly schedule portion.
