### ISSUE TITLE
Binary payload is not interpreted correctly

### ISSUE THREAD

**Issue by schmidtw** [Comcast/aker#102]
The binary payload below is not being interpreted correctly and is being discarded:
```84 A9 74 69 6D 65 5F 7A 6F 6E 65 B0 41 6D 65 72 69 63 61 2F 4E 65 77 5F 59 6F 72 6B A6 77 65 65 6B 6C 79 93 82 A4 74 69 6D 65 0A A7 69 6E 64 65 78 65 73 93 00 01 03 82 A4 74 69 6D 65 14 A7 69 6E 64 65 78 65 73 91 00 82 A4 74 69 6D 65 1E A7 69 6E 64 65 78 65 73 C0 A4 6D 61 63 73 94 B1 31 31 3A 32 32 3A 33 33 3A 34 34 3A 35 35 3A 61 61 B1 32 32 3A 33 33 3A 34 34 3A 35 35 3A 36 36 3A 62 62 B1 33 33 3A 34 34 3A 35 35 3A 36 36 3A 37 37 3A 63 63 B1 34 34 3A 35 35 3A 36 36 3A 37 37 3A 38 38 3A 64 64 A8 61 62 73 6F 6C 75 74 65 91 82 A9 75 6E 69 78 5F 74 69 6D 65 CE 59 E5 83 17 A7 69 6E 64 65 78 65 73 92 00 02```

**Comment by manderiasian** [comment]
What is this binary payload supposed to be?

**Comment by cableramki** [comment]
This one is fixed. The curl command needed tweaking,

curl -H "Authorization: Bearer $XMIDT_SAT" https://api-beta.xmidt.comcast.net/api/v2/device -H "X-Xmidt-Message-Type: Create" -H "X-Xmidt-Transaction-Uuid: bd4ad2d1-5c9c-486f-8e25-52c242b38f71" -H "X-Xmidt-Path: /aker/persistent/schedule" -H "X-Xmidt-Source: dns:ramki" -H "X-Webpa-Device-Name: mac:<mac id>/aker/schedule" --data-binary @pcs-wes.bin -X POST –I

**Comment by manderiasian** [comment]
closed

**Comment by manderiasian** [comment]
close #102
