### ISSUE TITLE
Handling of new schedule message

### ISSUE THREAD

**Issue by cableramki** [Comcast/aker#16]
1. Message owner of schedule using a message queue.
2. Replace schedule.
3. If step # 2 is success, write the new schedule msgpack binary to file.

**Comment by manderiasian** [comment]
No need for 1,2
If you look at my implementation (somewhat based on Wes' ideas) the scheduler detects file change based on file version which is maintained by the code (not part of OS or in the file itself)

**Comment by manderiasian** [comment]
And #3 has been implemented and working.

**Comment by schmidtw** [comment]
So this can be closed?

**Comment by manderiasian** [comment]
Close issue #14
