### ISSUE TITLE
Unixtime to weekly time needs to be written.

### ISSUE THREAD

**Issue by schmidtw** [Comcast/aker#26]
Right now the actual converter does nothing, but the unixtime to weekly time needs to be finished.  Of note - we need to ensure that the time changes are accounted for correctly.

Correct behavior for the time change:
- Only the most recent event in the window of time that is truncated is applied
- During the repeated windows of time, the schedule is also repeated as thou that there was not an immediate repeat.
- Ensure that the correct next event window is calculated so Aker doesn't sleep for too long.

**Comment by schmidtw** [comment]
Add some unit tests showing:
-during known DST windows we get the expected results (one springing forward & one falling back)
-during non DST shifts show that a couple values are right

Then this is done :)

**Comment by manderiasian** [comment]
I am confused Unix time to weekly time gets a time_t, does that already have  any DST applied to it?
Also, localtime() returns a value for "in DST", but the values are correct, how would we use the "in DST" to do any testing? And if the schedule transmitted was based on pre-dst change, ...too many questions.

**Comment by schmidtw** [comment]
This can be marked done because the tests in https://github.com/Comcast/aker/blob/master/tests/test_time_changes.c
