### ISSUE TITLE
RDK logger module override func to be patched in yocto

### ISSUE THREAD

**Issue by shilpa24balaji** [Comcast/aker#46]
https://github.com/Comcast/aker/blob/e5afc7830e0df776a62b8351d43ee07d82c3409e/src/main.c#L239
Add this function as patch in yocto and not here

**Comment by schmidtw** [comment]
https://github.com/Comcast/aker/commit/4f05b150cfe66949d355715ea19a72f2d80dc098#diff-803c5170888b8642f2a97e5e9423d399
