### ISSUE TITLE
Use key names for processing the input

### ISSUE THREAD

**Issue by schmidtw** [Comcast/aker#53]
We should use key names to process the input file, not just `key`:`value type` combos.  This will make the code significantly more robust.

**Comment by manderiasian** [comment]
Not sure if I understand "key names", what I see in msgpack_object is key/value.

**Comment by manderiasian** [comment]
I guess you could mean for example look at string name "time" and the key->type?

**Comment by schmidtw** [comment]
yeah, the string names "time" or "indexes" or "weekly" or "absolute"

**Comment by manderiasian** [comment]
So do you plan to change "unix-time" to "time" also? (It makes it more consistent)

**Comment by schmidtw** [comment]
I asked & they didn't want/need that change.

**Comment by manderiasian** [comment]
Issue completed 
https://github.com/Comcast/aker/pull/58

**Comment by manderiasian** [comment]
close #53
