### ISSUE TITLE
Clean up log messages

### ISSUE THREAD

**Issue by schmidtw** [Comcast/aker#56]
We want to make sure that the log messages are useful and helpful when debugging problems.  We need to ensure they are valuable and not too chatty.

**Comment by cableramki** [comment]
1. https://github.com/Comcast/aker/commit/faf01abf7ab5de4947f4a665906f2a09ac4120ff
2. https://github.com/Comcast/aker/commit/e8b757fc5a2ca6c5db9b1f550c4a72062b33beb2
