### ISSUE TITLE
Add md5 calculation, storage and verification

### ISSUE THREAD

**Issue by schmidtw** [Comcast/aker#57]
We want to calculate the MD5 checksum and store it on disk upon receipt and storage of the file.  Upon reading of the data file from disk, we want to re-check the MD5 to ensure the data was not corrupted.

**Comment by manderiasian** [comment]
Can we use 
https://github.com/gcc-mirror/gcc/blob/master/libiberty/md5.c

**Comment by manderiasian** [comment]
Or use crypt()/crypt_r()

**Comment by manderiasian** [comment]
I saw your question on https://gist.github.com/creationix/4710780, I saw  that code also and was wondering why it didn't have any copyright, etc ...

**Comment by manderiasian** [comment]
close issue #60
