### ISSUE TITLE
Add a test to confirm that all arrays can be empty or null

### ISSUE THREAD

**Issue by schmidtw** [Comcast/aker#77]
We need to ensure that we support arrays that are:

- [ ]  empty & present
- [ ] null & present
- [ ] not present

Without unintended side effects (like crashing).

**Comment by cableramki** [comment]
For _absolute_ schedule, need to ensure that any of the above can never be interpreted to:
```
    "absolute": [
        { "unix_time": 0, "indexes": null},
    ]
```

**Comment by manderiasian** [comment]
Just to be a little technical, and array is "[...]", and empty/null array is "[]"
Anything like {....} is a map. 
An it would be a syntax violation to have "Foo": "Another_Thing": 
In other words "not present" would mean the whole map is not present, i.e. "absolute": [...] is completely missing.  Which means we probably need to have a JSON validation routine (I think seshat had something similar)

**Comment by cableramki** [comment]
Following are the testcases Wes provided that need to be added:
1. "index": null == "index": []  ---->  block nothing
2. "index"  missing -----------------> error
3. "weekly": null == "weekly":[]  == no weekly schedule

**Comment by manderiasian** [comment]
OK, but can'r have {"index":} That would/must cause an error on the sever side.

**Comment by manderiasian** [comment]
Also, all of these MUST have consequences as far as the "scheduler" goes, errors such as missing "indexs" should not crash the code, but what is the "scheduler" supposed to do? Assume indexes did not change" Or just throw away the new schedule?

**Comment by schmidtw** [comment]
Yes, the payload needs to be valid msgpack, so { "index": } without either a `null` or empty array is invalid.

**Comment by cableramki** [comment]
How about just {} ? Is it valid?

**Comment by manderiasian** [comment]
Nop. "{}" is invalid msg pack.
