### ISSUE TITLE
Add `max-macs` command line argument to specifiy max blocked device macs

### ISSUE THREAD

**Issue by schmidtw** [Comcast/aker#83]
Instead of having a hard coded limit, it should come in via a command line option: `max-macs`.

If not specified or specified to `0`, then there is no limit.  The size of the `index` for each entry will be verified to be less then the limit specified.

**Comment by schmidtw** [comment]
Today the hard coded default is 128.

**Comment by manderiasian** [comment]
close #83

**Comment by cableramki** [comment]
As implemented now, this is a required argument. 

However, from the requirement "If not specified or ..." it seems this would need to be an optional argument.

**Comment by manderiasian** [comment]
Are u getting an error? i.e. required argument not specified?

**Comment by manderiasian** [comment]
@cableramki If you are getting an error send me the command line you are using.

**Comment by cableramki** [comment]
Hi @manderiasian, I have not seen an error. I was going by the code - https://github.com/Comcast/aker/blob/master/src/main.c#L76

**Comment by manderiasian** [comment]
The code is 100% correct.  I am adding some code to punish the user if they make a mistake ;-)
